web/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls", namespace='polls'))
]

web/mysite/polls/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path("login_success/", views.login_success, name="login_success"),
]

web/mysite/polls/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'member'

web/mysite/polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Hello, world")

def login(request):
    return redirect('polls:login_success')

def login_success(request):
    return render(request, "login_success.html")

web/mysite/polls/templates/polls/login.html
<form action="{% url 'polls:login' %}" method="post">
    {% csrf_token %}
    <input type="input" name="username" placeholder="username">
    <input type="password" name="password" placeholder="password">
    <input type="submit" value="Login">
  </form>

web/mysite/polls/templates/polls/login_success.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>로그인 정보 확인</title>
</head>
<body>
    <h1>로그인 성공!</h1>
</body>
</html>